name: CD pipeline

on:
  workflow_run:
    workflows: [ "CI pipeline" ]
    types:
    - completed


jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Pull docker image
      run: sudo docker pull maulika/cicd-pipeline:latest
    - name: Delete old container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run docker container
      run: sudo docker run -d -p 8501:8501 --name cicd-pipeline-container maulika/cicd-pipeline